# For Testing read README.md Test section
@baseUrl = {{$dotenv URL}}:{{$dotenv PORT}}{{$dotenv ROOT_PATH}}
@key = {{$dotenv KEY}}
@path = api-keys

# GET ALL API KEYS
GET {{baseUrl}}/{{path}}
authorization: {{key}}

###

# CREATE API KEYS - Failed
POST {{baseUrl}}/{{path}}
authorization: {{key}}
content-type: application/json

{
  "name": "TEST12",
  "createdBy": "pepito"
}

###

# CREATE API KEYS - Successfully
POST {{baseUrl}}/{{path}}
authorization: {{key}}
content-type: application/json

{
  "name": "TEST",
  "createdBy": "frodriguez"
}

###

# DELETE API KEYS
DELETE {{baseUrl}}/{{path}}/TEST
authorization: {{key}}

###s