# For Testing read README.md Test section
@baseUrl = {{$dotenv URL}}:{{$dotenv PORT}}{{$dotenv ROOT_PATH}}
@key = {{$dotenv API_KEY}}
@path = auth
# AUTH USER
POST {{baseUrl}}/{{path}}
authorization: {{key}}
Content-Type: application/json

{
  "username": "frodriguez",
  "password": "test123"
}

###