# For Testing read README.md Test section
@baseUrl = {{$dotenv URL}}:{{$dotenv PORT}}{{$dotenv ROOT_PATH}}
@key = {{$dotenv API_KEY}}

# GET ALL BLACKLIST
GET {{baseUrl}}/blacklist
authorization: {{key}}

###