# For Testing read README.md Test section
@baseUrl = {{$dotenv URL}}:{{$dotenv PORT}}{{$dotenv ROOT_PATH}}
@key = {{$dotenv API_KEY}}
@path = blacklist

# GET ALL BLACKLIST
GET {{baseUrl}}/{{path}}
authorization: {{key}}

###

# CREATE BLACKLIST - Failed
POST {{baseUrl}}/{{path}}
authorization: {{key}}
content-type: application/json

{
  "clientId": "000026",
  "reason": "Razón de ejemplo",
  "createdBy": "mario"
}

###

# CREATE BLACKLIST - Successfully
POST {{baseUrl}}/{{path}}
authorization: {{key}}
content-type: application/json

{
  "clientId": "000026",
  "reason": "Deudor FTTH",
  "createdBy": "frodriguez"
}

###

# UPDATE BLACKLIST
PATCH {{baseUrl}}/{{path}}/000026
authorization: {{key}}
content-type: application/json

{
  "reason": "Actualización del motivo.",
  "createdBy": "frodriguez"
}

###

# DELETE BLACKLIST
DELETE {{baseUrl}}/{{path}}/000026
authorization: {{key}}

###