# For Testing read README.md Test section
@baseUrl = {{$dotenv URL}}:{{$dotenv PORT}}{{$dotenv ROOT_PATH}}
@key = {{$dotenv API_KEY}}
@path = clients

# GET ALL CLIENTS
GET {{baseUrl}}/{{path}}
authorization: {{key}}

###

# CREATE CLIENT - Failed
POST {{baseUrl}}/{{path}}
authorization: {{key}}
content-type: application/json

{
  "id": "asadssd"
}

###

# CREATE CLIENT - Successfully
POST {{baseUrl}}/{{path}}
authorization: {{key}}
content-type: application/json

{
  "firstName": "Franco Germán",
  "lastName": "Rodríguez Llovera",
  "document": 44990850,
  "email": "frodriguez@netse.com.ar",
  "address": {
    "province": "Buenos Aires",
    "neighborhood": "Parque Patricio",
    "direction": "Lavárden 43"
  },
  "coordinates": {
    "lat": -34.636966,
    "lng": -58.402071
  }
}

###

# GET CLIENT BY ID
GET {{baseUrl}}/{{path}}/1
authorization: {{key}}

###

# DELETE CLIENT
DELETE {{baseUrl}}/{{path}}/2
authorization: {{key}}

###

# UPDTATE CLIENT
PATCH {{baseUrl}}/{{path}}/1
authorization: {{key}}
content-type: application/json

{
  "sql": "SELECT * FROM user",
  "email": "frodriguez@netse.com.ar"
}