# For Testing read README.md Test section
@baseUrl = {{$dotenv URL}}:{{$dotenv PORT}}{{$dotenv ROOT_PATH}}
@key = {{$dotenv API_KEY}}
@path = groups

# GET ALL GROUPS
GET {{baseUrl}}/{{path}}?key={{key}}

###

# CREATE GROUP - Failed
POST {{baseUrl}}/{{path}}
content-type: application/json

{
  "key": "{{key}}"
}

###

# CREATE GROUP - Successfully
POST {{baseUrl}}/{{path}}
authorization: {{key}}
content-type: application/json

{
  "name": "testGroup",
  "towers": "TODO"
}

###

# GET GROUP BY NAME
GET {{baseUrl}}/{{path}}/testGroup
authorization: {{key}}

###

# DELETE GROUP
DELETE {{baseUrl}}/{{path}}/testGroup
authorization: {{key}}

###

# UPDTATE A GROUP
PATCH {{baseUrl}}/{{path}}/testGroup
authorization: {{key}}
content-type: application/json

{
  "sql": "SELECT * FROM user",
  "towers": "CHANGE"
}