# For Testing read README.md Test section
@baseUrl = {{$dotenv URL}}:{{$dotenv PORT}}{{$dotenv ROOT_PATH}}
@key = {{$dotenv API_KEY}}
@path = tokens

# GET ALL TOKENS
GET {{baseUrl}}/{{path}}
authorization: {{key}}

###

# CREATE TOKEN - Failed
POST {{baseUrl}}/{{path}}
authorization: {{key}}
content-type: application/json

{
    "tokenName": "TEST12",
    "username": "pepito"
}

###

# CREATE TOKEN - Successfully
POST {{baseUrl}}/{{path}}
authorization: {{key}}
content-type: application/json

{
    "tokenName": "TEST",
    "username": "frodriguez"
}

###

# DELETE TOKEN
DELETE {{baseUrl}}/{{path}}/TEST
authorization: {{key}}

###s