# For Testing read README.md Test section
@baseUrl = {{$dotenv URL}}:{{$dotenv PORT}}{{$dotenv ROOT_PATH}}
@key = {{$dotenv KEY}}
@path = tokens

# GET ALL TOKENS
GET {{baseUrl}}/{{path}}
authorization: {{key}}

###

# CREATE TOKEN - Failed
POST {{baseUrl}}/{{path}}
authorization: {{key}}
content-type: application/json

{
  "name": "TEST12",
  "createdBy": "pepito"
}

###

# CREATE TOKEN - Successfully
POST {{baseUrl}}/{{path}}
authorization: {{key}}
content-type: application/json

{
  "name": "TEST",
  "createdBy": "frodriguez"
}

###

# DELETE TOKEN
DELETE {{baseUrl}}/{{path}}/TEST
authorization: {{key}}

###s