# For Testing read README.md Test section
@baseUrl = {{$dotenv URL}}:{{$dotenv PORT}}{{$dotenv ROOT_PATH}}
@key = {{$dotenv KEY}}

# GET ALL USERS
GET {{baseUrl}}/users
authorization: {{key}}

###

# CREATE USER - Failed
POST {{baseUrl}}/users
authorization: {{key}}
content-type: application/json

{
    "username": "frodriguez"
}

###

# CREATE USER - Successfully
POST {{baseUrl}}/users
authorization: {{key}}
content-type: application/json

{
    "username": "rmoreno",
    "firstName": "Richard",
    "lastName": "Moreno",
    "email": "rmoreno@gmail.com",
    "rol": "Coordinador"
}

###

# GET USERS BY USERNAME
GET {{baseUrl}}/users/frodriguez
authorization: {{key}}

###

# DELETE USER
DELETE {{baseUrl}}/users/flloveras
authorization: {{key}}

###

# UPDTATE A USER
PATCH {{baseUrl}}/users/frodriguez
authorization: {{key}}
content-type: application/json

{
    "sql": "SELECT * FROM user",
    "username": "flloveras",
    "email": "flloveras@netse.com.ar"
}