export const USER_PATH = '/users'
export const AUTH_PATH = '/auth'
export const TOKEN_PATH = '/tokens'
export const BLACKLIST_PATH = '/blacklist'
export const SERVICE_PATH = '/services'
export const PLAN_PATH = '/plans'
export const ADDITIONAL_PATH = '/additional'
